const js = require('@eslint/js');

module.exports = [
    js.configs.recommended,
    {
        files: ['src/**/*.js', 'lib/**/*.js', 'scripts/**/*.js', 'bot.js'],
        ignores: ['node_modules/**', 'logs/**', 'coverage/**'],
        languageOptions: {
            ecmaVersion: 2022,
            sourceType: 'script',
            globals: {
                require: 'readonly',
                module: 'readonly',
                __dirname: 'readonly',
                __filename: 'readonly',
                process: 'readonly',
                console: 'readonly',
                Buffer: 'readonly',
                setTimeout: 'readonly',
                clearTimeout: 'readonly',
                setInterval: 'readonly',
                clearInterval: 'readonly',
                fetch: 'readonly',
                AbortSignal: 'readonly',
                URL: 'readonly',
                TextEncoder: 'readonly',
                TextDecoder: 'readonly',
                Promise: 'readonly',
                Map: 'readonly',
                Set: 'readonly',
                Date: 'readonly',
                Math: 'readonly',
                JSON: 'readonly',
                Error: 'readonly',
                RegExp: 'readonly',
                parseInt: 'readonly',
                parseFloat: 'readonly',
                String: 'readonly',
                Number: 'readonly',
                Boolean: 'readonly',
                Object: 'readonly',
                Array: 'readonly',
                Symbol: 'readonly',
                BigInt: 'readonly',
                exports: 'readonly',
            },
        },
        rules: {
            'no-unused-vars': ['warn', { argsIgnorePattern: '^_' }],
            'no-console': 'off',
            'prefer-const': 'warn',
            'no-var': 'warn',
            'eqeqeq': ['warn', 'always'],
            'semi': ['warn', 'always'],
            'quotes': ['warn', 'single', { avoidEscape: true, allowTemplateLiterals: true }],
            'no-empty': ['warn', { allowEmptyCatch: true }],
        },
    },
    {
        files: ['tests/**/*.js'],
        languageOptions: {
            ecmaVersion: 2022,
            sourceType: 'script',
            globals: {
                require: 'readonly',
                module: 'readonly',
                __dirname: 'readonly',
                describe: 'readonly',
                it: 'readonly',
                expect: 'readonly',
                beforeEach: 'readonly',
                afterEach: 'readonly',
                beforeAll: 'readonly',
                afterAll: 'readonly',
                jest: 'readonly',
            },
        },
    },
];
